<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.bakuplayz.cropclick</groupId>
    <artifactId>CropClick</artifactId>
    <version>3.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <java.version>8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <PLUGIN_JAR_NAME>CropClick ${project.version}</PLUGIN_JAR_NAME>
    </properties>

    <modules>
        <module>common</module>
        <module>shared</module>
        <module>abstraction</module>
        <module>legacy</module>
        <module>latest</module>
    </modules>
</project>
