# ~~~~~~~~~~~~
# Developer: BakuPlayz
# Discord-Server: https://discord.gg/HqQqz2Z
# Spigot-Resource: https://www.spigotmc.org/resources/craftinggui.72420/
# ~~~~~~~~~~~~
# Issue reports:
# 1. Report issue via spigot (Response takes at max a week)
# 2. Report issue via discord (Response takes at max three days)
# ~~~~~~~~~~~~

updateMessage:
  player: true
  console: true

interact:
  jump: true
  leftClick: true
  rightClick: true

autofarm:
  isEnabled: true
  canHarvest:
    - beetroot
    - carrot
    - cocoaBean
    - potato
    - wheat

linkable:
  crops:
    - beetroot
    - cactus
    - carrot
    - cocoaBean
    - potato
    - sugarCane
    - wheat
  containers:
    - chest
    - shulker

particles: [ ]

sounds: [ ]