name: CropClick
author: BakuPlayz
version: ${project.version}
main: com.github.bakuplayz.cropclick.CropClick

softdepend:
  - Jobs
  - mcMMO
  - Residence
  - Towny
  - WorldEdit
  - WorldGuard

commands:
  cropclick:
    usage: /<command> []
    aliases: [ crop ]
    description: "Base command for the plugin: CropClick."

permissions:
  cropclick.*:
    description: Permission to access & use everything in CropClick.
    default: op
    children:
      - cropclick.plant.*
      - cropclick.harvest.*
      - cropclick.destroy.*
      - cropclick.command.*
      - cropclick.autofarm.*

  cropclick.autofarm.*:
    description: Permission to use all the autofarm features.
    default: op
    children:
      cropclick.autofarm.claim:
        description: Permission to claim an unknown own-owned autofarms.
      cropclick.autofarm.link:
        description: Permission to link your own autofarms.
      cropclick.autofarm.unlink:
        description: Permission to unlink your own autofarms.
      cropclick.autofarm.unlink.others:
        description: Permission to unlink others autofarms.
      cropclick.autofarm.update:
        description: Permission to update you own autofarms.
      cropclick.autofarm.update.others:
        description: Permission to update others autofarms.
      cropclick.autofarm.toggle:
        description: Permission to toggle your own autofarms.
      cropclick.autofarm.toggle.others:
        description: Permission to toggle others autofarms.
      cropclick.autofarm.interact:
        description: Permission to interact with your own autofarms.
      cropclick.autofarm.interact.others:
        description: Permission to interact with others autofarms.