name: CropClick
author: BakuPlayz
version: ${project.version}
main: com.github.bakuplayz.cropclick.CropClick

softdepend:
  - Jobs
  - mcMMO
  - Residence
  - Towny
  - WorldEdit
  - WorldGuard

commands:
  cropclick:
    usage: /<command> []
    aliases: [ crop ]
    description: "Base command for the plugin: CropClick."

permissions:
  cropclick.*:
    description: Permission to access & use everything in CropClick.
    default: op
    children:
      - cropclick.plant.*
      - cropclick.harvest.*
      - cropclick.destroy.*
      - cropclick.command.*
      - cropclick.autofarm.*

  cropclick.autofarm.*:
    description: Permission to use all the autofarm features.
    default: op
    children:
      cropclick.autofarm.link:
        description: Permission to link autofarms.
      cropclick.autofarm.unlink:
        description: Permission to unlink autofarms.
      cropclick.autofarm.update:
        description: Permission to update autofarms.
      cropclick.autofarm.toggle:
        description: Permission to toggle autofarms.
      cropclick.autofarm.interact:
        description: Permission to interact with autofarms.